### ISSUE TITLE
login小bug

### ISSUE THREAD

**Issue by DukeofCambridge** [HOLLYwyh/2021-sse-db-project#26]
保存密码按钮点击后无法取消

**Comment by HOLLYwyh** [comment]
@lightmountainwolf 恒哥快来修BUG

**Comment by DukeofCambridge** [comment]
对了，登录界面输入密码时点击不可见后能看到密码，点击可见后看不到密码，虽然也不是什么大问题，希望可以颠过来

**Comment by HOLLYwyh** [comment]
> 对了，登录界面输入密码时点击不可见后能看到密码，点击可见后看不到密码，虽然也不是什么大问题，希望可以颠过来

登录界面好像没有点击不可见这个按钮啊

**Comment by DukeofCambridge** [comment]
> > 对了，登录界面输入密码时点击不可见后能看到密码，点击可见后看不到密码，虽然也不是什么大问题，希望可以颠过来
> 
> 登录界面好像没有点击不可见这个按钮啊

输密码的时候右边会出现一个眼睛，可能是引用没改

**Comment by HOLLYwyh** [comment]
emmmm你用的是火狐浏览器吗？  这个我感觉好像是浏览器的问题我这里的Chrome好像没有这个问题

**Comment by DukeofCambridge** [comment]
小瑕疵，无所谓了，我就随手记一下

**Comment by HOLLYwyh** [comment]
阿巴阿巴
